language: python
install: pip install tox
script: tox -v -e $TOX_ENV -- --verbose
env:
  - TOX_ENV=docs
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
notifications:
  email:
    - jhubert@gmail.com
    - chiricagheorghe@gmail.com